# Сообщение при заходе на лодку/вагонетку и т.д
message: "&cУ Вас нету прав чтобы пользоваться данным энтити!"

# Право которое даст использовать лодку/вагонетку и т.д.
permission: "dboatfixer.use"

# Список запрещённых.
vehicles:
  - BOAT